# configs/augmentation_configs/basic_augmentation.yaml
augmentation:
  use_augmentation: true
  transforms:
    - name: SomeOf
      params:
        p: 0.5
        n: 1
        transforms:
          - name: RandomResizedCrop
            params:
              height: 512
              width: 512
              scale: [0.5, 1.0]
              p: 0.5
          - name: Rotate
            params:
              limit: 10
              p: 0.5
    - name: RandomBrightnessContrast
      params:
        p: 0.2
    - name: HueSaturationValue
      params:
        hue_shift_limit: 20
        sat_shift_limit: 30
        val_shift_limit: 20
        p: 0.5
    - name: HorizontalFlip
      params:
        p: 0.5
