_wandb:
    value:
        cli_version: 0.18.2
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 9
                - 41
                - 55
                - 103
            "2":
                - 1
                - 9
                - 41
                - 55
                - 103
            "3":
                - 2
                - 23
                - 55
            "4": 3.10.13
            "5": 0.18.2
            "8":
                - 1
                - 5
            "12": 0.18.2
            "13": linux-x86_64
